name: TextAttack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Navigate to the textattack directory
    - name: Change to textattack directory
      run: cd ./textattack

    # Build the Docker image using the ./textattack directory as context
    - name: Build Docker image
      run: docker build -t textattack-test ./textattack

    # Run the container
    - name: Run Docker container
      run: docker run textattack-test
